name: library

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    # linuxserver.io containers do not support `user: "1000:1000"`
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Almaty
      - CALIBRE_LIBRARY_PATH=/books
    volumes:
      - calibre-config:/config
      - books:/books
    ports:
      - 8083:8083
    restart: no

  webdav:
    image: rclone/rclone:latest
    container_name: moon-webdav
    user: "1000:1000"
    environment:
      - TZ=Asia/Almaty
    volumes:
      - data:/data
    ports:
      - 8084:8084
    command: serve webdav /data --addr :8084 --user admin --pass admin123
    restart: no

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/encrypted/webdav
  calibre-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/encrypted/apps/calibre-config
  books:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/books
