services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: no
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Almaty
      - LOG_LEVEL=2 # Standard logging
    volumes:
      - ./smb.conf:/etc/samba/smb.conf:ro
      - vault:/share/vault
      - gallery:/share/gallery
      - books:/share/books
    ports:
      - "445:445" # SMB/CIFS (Modern Windows)
      - "139:139" # NetBIOS Session Service (Legacy)

volumes:
  vault:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/encrypted/vault
  gallery:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/gallery
  books:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/books
