services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: no
    environment:
      - TZ=Asia/Almaty
      - LOG_LEVEL=2 # Standard logging
    # Configure everything directly via container command parameters:
    command: >
      -u "${SAMBA_USER};${SAMBA_USER_PASSWORD};1000;${SAMBA_USER};1000"
      -s "vault;/share/vault;yes;no;no;${SAMBA_USER};none;${SAMBA_USER}"
      -s "webdav;/share/webdav;yes;no;no;${SAMBA_USER};none;${SAMBA_USER}"
      -s "apps;/share/apps;yes;no;no;${SAMBA_USER};none;${SAMBA_USER}"
      -s "gallery;/share/gallery;yes;no;no;${SAMBA_USER};none;${SAMBA_USER}"
      -s "books;/share/books;yes;no;no;${SAMBA_USER};none;${SAMBA_USER}"
      -s "downloads;/share/downloads;yes;no;no;${SAMBA_USER};none;${SAMBA_USER}"
      -g "force user = ${SAMBA_USER}"
      -g "force group = ${SAMBA_USER}"
    volumes:
      - vault:/share/vault
      - gallery:/share/gallery
      - books:/share/books
      - apps:/share/apps
    ports:
      - "445:445" # SMB/CIFS (Modern Windows)
      - "139:139" # NetBIOS Session Service (Legacy)

volumes:
  vault:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/encrypted/vault
  apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/encrypted/apps
  webdav:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/encrypted/webdav
  gallery:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/gallery
  books:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/books
  downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/downloads
