[global]
    workgroup = WORKGROUP
    server string = Utsuwa NAS
    security = user
    map to guest = Bad User
    log file = /var/log/samba/%m.log
    max log size = 50
    dns proxy = no

[vault]
    comment = Personal Vault
    path = /share/vault
    browseable = yes
    writable = yes
    guest ok = no
    valid users = 1000
    force user = 1000
    force group = 1000
    create mask = 0660
    directory mask = 0770

[gallery]
    comment = Gallery
    path = /share/gallery
    browseable = yes
    writable = yes
    guest ok = no
    valid users = 1000
    force user = 1000
    force group = 1000
    create mask = 0660
    directory mask = 0770

[books]
    comment = Books
    path = /share/books
    browseable = yes
    writable = yes
    guest ok = no
    valid users = 1000
    force user = 1000
    force group = 1000
    create mask = 0660
    directory mask = 0770